[Settings]
ID = "gatsby-wunder"

# The following show an example redirects rule with all the supported properties.
[[redirects]]
  from = "/foo"
  to = "/blog"
  status = 301
  force = false
  query = {path = ":path"} # apply this rule for /old-path?path=example
  # NOTE: Each combination of query params will need to be defined in a separate [[redirects]] block. More here: https://www.netlify.com/docs/redirects/#query-params
  # conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
  # you can use env variables you've set in the UI or within your contexts as values
  # sign each request with the value of this env variable
  signed = "17505835-638f-411f-94bf-95c4e7e2ca9c"
  # NOTE: env variables are only natively supported for this signed property of headers via this mechanism!
  # You can also define custom headers within your redirects blocks
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "17505835-638f-411f-94bf-95c4e7e2ca9c"